"""OAuth request, failure, credential-rotation and harness tests. No live requests."""
import argparse
import io
import json
import os
from pathlib import Path
import sys
import tempfile
import threading
import time
import unittest
from unittest.mock import patch, Mock
from urllib.error import HTTPError

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "src"), str(ROOT / "scripts"), str(ROOT / "third_party/robodawn")]
from branchlab import oauth
from branchlab.vlm import VLM
from harness.agent.llm_client import ChatClient
import run_robodawn_relay as relay
import oauth_experiments

MESSAGES = [{"role": "system", "content": "robot instructions"},
            {"role": "user", "content": [{"type": "text", "text": "demo"},
             {"type": "image_url", "image_url": {"url": "data:image/png;base64,YWJj", "detail": "high"}}]},
            {"role": "assistant", "content": "old action"}, {"role": "user", "content": "next turn"}]
BODY = {"model": "gpt-test", "messages": MESSAGES, "max_tokens": 8000, "temperature": 0}


def sse(payload=None, event="response.completed"):
    payload = payload or {"id": "r1", "model": "gpt-test", "status": "completed",
                          "output": [{"type": "message", "content": [{"type": "output_text", "text": "OK"}]}],
                          "usage": {"input_tokens": 10, "output_tokens": 5,
                                    "output_tokens_details": {"reasoning_tokens": 3}}}
    return io.BytesIO(("event: " + event + "\ndata: " + json.dumps({"type": event, "response": payload}) + "\n\n").encode())


def claude_sse():
    events = [{"type": "message_start", "message": {"id": "c1", "model": "claude-test", "content": [],
               "usage": {"input_tokens": 10, "output_tokens": 1}}},
              {"type": "content_block_start", "index": 0, "content_block": {"type": "text", "text": ""}},
              {"type": "content_block_delta", "index": 0, "delta": {"type": "text_delta", "text": "OK"}},
              {"type": "message_delta", "delta": {"stop_reason": "end_turn"}, "usage": {"output_tokens": 2}},
              {"type": "message_stop"}]
    return io.BytesIO("".join("data: " + json.dumps(event) + "\n\n" for event in events).encode())


class OAuthTests(unittest.TestCase):
    def setUp(self):
        self.network = patch.object(oauth, "open_request", side_effect=AssertionError("Unexpected network call"))
        self.network.start()
        self.addCleanup(self.network.stop)

    def test_multimodal_history_and_unsupported_gpt_parameters(self):
        native = oauth.request_body(BODY, "openai-oauth")
        self.assertEqual([m["role"] for m in native["input"]], ["developer", "user", "assistant", "user"])
        self.assertEqual(native["input"][1]["content"][1],
                         {"type": "input_image", "image_url": "data:image/png;base64,YWJj", "detail": "high"})
        self.assertEqual(native["input"][2]["content"], [{"type": "output_text", "text": "old action"}])
        self.assertNotIn("temperature", native)
        self.assertNotIn("max_output_tokens", native)
        self.assertFalse(native["store"])
        self.assertTrue(native["stream"])

    def test_anthropic_preserves_images_system_and_effort(self):
        native = oauth.request_body({**BODY, "model": "anthropic/claude-test", "reasoning_effort": "high"}, "anthropic-oauth")
        self.assertEqual(native["system"][1:], [{"type": "text", "text": "robot instructions"}])
        self.assertTrue(native["system"][0]["text"].startswith("x-anthropic-billing-header:"))
        self.assertEqual(native["messages"][0]["content"][1]["source"]["data"], "YWJj")
        self.assertEqual(native["max_tokens"], 8000)  # explicit caller override
        self.assertTrue(native["stream"])
        self.assertEqual(native["thinking"], {"type": "adaptive"})
        self.assertNotIn("temperature", native)
        self.assertEqual(native["model"], "claude-test")

    def test_billing_marker_matches_javascript_unicode_vectors(self):
        # Expected hashes independently generated by Node crypto using the
        # reference's UTF-16 text[position] and UTF-8 TextEncoder semantics.
        vectors = [("Reply with exactly OK.", "b05", "b4d50"),
                   ("😀hello world test message", "00a", "46c54"),
                   ("abcd😀x😀abcdefghijk😀", "d1f", "632e2"),
                   ("", "8a8", "e3b0c"), ("a\ud800z", "8a8", "e8fff")]
        for text, suffix, cch in vectors:
            with self.subTest(text=text):
                marker = oauth.claude_billing_marker([{"role": "user", "content": [{"type": "text", "text": text}]}])
                self.assertEqual(marker, f"x-anthropic-billing-header: cc_version=2.1.295.{suffix}; "
                                 f"cc_entrypoint=sdk-cli; cch={cch};")

    def test_billing_uses_first_user_text_block_only(self):
        first = {"role": "user", "content": [{"type": "image"}, {"type": "text", "text": "Reply with exactly OK."},
                                             {"type": "text", "text": "ignored"}]}
        marker = oauth.claude_billing_marker([{"role": "assistant", "content": [{"type": "text", "text": "ignored"}]},
                                             first, {"role": "user", "content": [{"type": "text", "text": "ignored"}]}])
        self.assertIn("cc_version=2.1.295.b05;", marker)
        self.assertIn("cch=b4d50;", marker)

    def test_unknown_parts_fields_and_remote_images_rejected(self):
        for body in ({**BODY, "tools": []}, {**BODY, "messages": [{"role": "tool", "content": "x"}]},
                     {**BODY, "messages": [{"role": "user", "content": [
                      {"type": "image_url", "image_url": {"url": "https://example.org/x.png"}}]}]}):
            with self.assertRaises(ValueError):
                oauth.request_body(body, "openai-oauth")

    def test_sse_requires_successful_terminal_event(self):
        self.assertEqual(oauth.sse_response(sse())["model"], "gpt-test")
        for response in (io.BytesIO(b'data: {"type":"response.output_text.delta","delta":"partial"}\n\n'),
                         sse(event="response.failed"), sse(event="response.incomplete")):
            with self.assertRaises(oauth.OAuthError):
                oauth.sse_response(response)

    def test_anthropic_cache_accounting_and_unknown_reasoning(self):
        result = oauth.normalized({"model": "claude-test", "content": [{"type": "thinking", "thinking": "hidden"},
                                  {"type": "text", "text": "OK"}],
                                  "usage": {"input_tokens": 10, "output_tokens": 4, "cache_read_input_tokens": 20,
                                            "cache_creation_input_tokens": 30}}, "anthropic-oauth")
        self.assertEqual(result["usage"]["prompt_tokens"], 60)
        self.assertEqual(result["usage"]["total_tokens"], 64)
        self.assertNotIn("reasoning_tokens", result["usage"]["completion_tokens_details"])
        self.assertEqual(result["choices"][0]["message"]["content"], "OK")

    def test_refresh_once_on_401_and_no_secret_in_error(self):
        credentials = Mock()
        credentials.get.side_effect = [{"access_token": "SECRET"}, {"access_token": "NEW"}]
        transport = oauth.OAuthTransport("openai-oauth", credentials)
        with patch.object(oauth, "open_request", side_effect=[HTTPError("url", 401, "SECRET", {}, None), sse()]) as send:
            result = transport.send(BODY)
        self.assertEqual(result["model"], "gpt-test")
        self.assertEqual(send.call_count, 2)
        credentials.get.assert_called_with("SECRET")
        with patch.object(oauth, "open_request", side_effect=HTTPError("SECRET", 403, "SECRET", {}, None)):
            with self.assertRaises(oauth.OAuthError) as raised:
                oauth.OAuthTransport("openai-oauth", Mock(get=lambda _: {"access_token": "SECRET"})).send(BODY)
        self.assertNotIn("SECRET", str(raised.exception))
        self.assertEqual(raised.exception.status, 403)

    def test_environment_token_never_falls_back_to_api_key(self):
        with patch.dict(os.environ, {"OPENAI_API_KEY": "not-oauth"}, clear=True):
            with self.assertRaises(oauth.OAuthError):
                oauth.Credentials("openai-oauth").get()
        with patch.dict(os.environ, {"OPENAI_OAUTH_ACCESS_TOKEN": "oauth"}, clear=True):
            with self.assertRaises(oauth.OAuthError):
                oauth.Credentials("openai-oauth").get("oauth")

    def test_codex_endpoint_and_account_header(self):
        credentials = Mock(get=lambda _: {"access_token": "token", "account_id": "account"})
        with patch.object(oauth, "open_request", return_value=sse()) as send:
            oauth.OAuthTransport("openai-codex-oauth", credentials).send(BODY)
        request = send.call_args.args[0]
        self.assertEqual(request.full_url, oauth.ENDPOINTS["openai-codex-oauth"])
        self.assertEqual(request.get_header("Chatgpt-account-id"), "account")
        self.assertIn("instructions", json.loads(request.data))

    def test_anthropic_http_matches_reference_profile_preserving_prompt(self):
        credentials = Mock(get=lambda _: {"access_token": "token"})
        with patch.object(oauth, "open_request", return_value=claude_sse()) as send:
            result = oauth.OAuthTransport("anthropic-oauth", credentials).send({"model": "claude-test", "messages": MESSAGES})
        request = send.call_args.args[0]
        self.assertEqual(send.call_count, 1)
        self.assertEqual(request.full_url, oauth.ENDPOINTS["anthropic-oauth"])
        self.assertEqual(json.loads(request.data)["max_tokens"], 64000)
        self.assertTrue(json.loads(request.data)["stream"])
        self.assertEqual(request.get_header("Authorization"), "Bearer token")
        self.assertNotIn("X-api-key", request.headers)
        self.assertEqual(request.get_header("Anthropic-beta"), oauth.CLAUDE_BETAS)
        self.assertEqual(request.get_header("Anthropic-dangerous-direct-browser-access"), "true")
        self.assertEqual(request.get_header("Accept"), "text/event-stream, application/json")
        self.assertEqual(json.loads(request.data)["system"][1:], [{"type": "text", "text": "robot instructions"}])
        self.assertEqual(result["request_profile"], oauth.CLAUDE_COMPAT_VERSION)
        self.assertEqual(result["choices"][0]["finish_reason"], "end_turn")
        self.assertEqual(result["choices"][0]["message"]["content"], "OK")
        self.assertEqual(result["usage"]["completion_tokens"], 2)
        self.assertEqual(result["output_token_limit"], {"policy": "configured", "max_tokens": 64000})

    def test_claude_budget_defaults_overrides_and_invalid_values(self):
        body = {"model": "claude-test", "messages": MESSAGES}
        self.assertEqual(oauth.request_body(body, "anthropic-oauth")["max_tokens"], 64000)
        self.assertEqual(oauth.request_body({**body, "max_tokens": 32000}, "anthropic-oauth")["max_tokens"], 32000)
        for invalid in (0, -1, None, True):
            with self.assertRaises(ValueError):
                oauth.request_body({**body, "max_tokens": invalid}, "anthropic-oauth")
        client = oauth.oauth_client(ChatClient, "anthropic-oauth")(model="claude-test", max_tokens=8000)
        self.assertEqual(client._body(MESSAGES)["max_tokens"], 64000)

    def test_claude_interrupted_stream_is_not_success(self):
        with self.assertRaisesRegex(oauth.OAuthError, "message_stop"):
            oauth.anthropic_response(io.BytesIO(b'data: {"type":"message_start","message":{"model":"claude-test"}}\n\n'))

    def test_gpt_needs_no_budget_and_never_sends_one(self):
        for backend in ("openai-oauth", "openai-codex-oauth"):
            body = {k: v for k, v in BODY.items() if k != "max_tokens"}
            native = oauth.request_body(body, backend)
            self.assertNotIn("max_tokens", native)
            self.assertNotIn("max_output_tokens", native)

    def test_second_401_stops_and_redirect_is_not_followed(self):
        credentials = Mock(get=lambda _: {"access_token": "token"})
        with patch.object(oauth, "open_request", side_effect=HTTPError("url", 401, "secret", {}, None)) as send:
            with self.assertRaises(oauth.OAuthError) as raised:
                oauth.OAuthTransport("openai-oauth", credentials).send(BODY)
            self.assertEqual(send.call_count, 2)
            self.assertEqual(raised.exception.status, 401)
        with self.assertRaises(oauth.OAuthError):
            oauth.NoRedirect().redirect_request(None, None, 302, "secret", {}, "https://other.example")

    def test_failed_refresh_preserves_credential_file(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "auth.json"
            path.write_text(json.dumps({"access_token": "old", "refresh_token": "secret", "client_id": "c", "expires_at": 1}))
            path.chmod(0o600)
            before = path.read_bytes()
            with patch.object(oauth, "open_request", side_effect=HTTPError("secret", 400, "secret", {}, None)):
                with self.assertRaises(oauth.OAuthError) as raised:
                    oauth.Credentials("openai-oauth", path).get()
                self.assertNotIn("secret", str(raised.exception))
            self.assertEqual(path.read_bytes(), before)

    def test_private_file_and_rotated_refresh_are_persisted(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "auth.json"
            path.write_text(json.dumps({"access_token": "old", "refresh_token": "refresh-old", "client_id": "test",
                                        "expires_at": 1}))
            path.chmod(0o600)
            with patch.object(oauth, "open_request", return_value=io.BytesIO(json.dumps(
                    {"access_token": "new", "refresh_token": "refresh-new", "expires_in": 3600}).encode())) as send:
                auth = oauth.Credentials("openai-oauth", path)
                self.assertEqual(auth.get()["access_token"], "new")
                self.assertEqual(auth.get("old")["access_token"], "new")
                self.assertEqual(send.call_count, 1)
            self.assertEqual(json.loads(path.read_text())["refresh_token"], "refresh-new")
            self.assertEqual(path.stat().st_mode & 0o777, 0o600)
            path.chmod(0o644)
            with self.assertRaises(oauth.OAuthError):
                auth.get()
            path.chmod(0o600)
            link = Path(directory) / "link.json"
            link.symlink_to(path)
            with self.assertRaises(oauth.OAuthError):
                oauth.Credentials("openai-oauth", link).get()

    def test_multiple_workers_refresh_once(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "auth.json"
            path.write_text(json.dumps({"access_token": "old", "refresh_token": "r", "client_id": "c", "expires_at": 1}))
            path.chmod(0o600)
            results = []
            def refresh(*args):
                time.sleep(0.02)
                return io.BytesIO(b'{"access_token":"new","expires_in":3600}')
            with patch.object(oauth, "open_request", side_effect=refresh) as send:
                workers = [threading.Thread(target=lambda: results.append(oauth.Credentials("openai-oauth", path).get()))
                           for _ in range(4)]
                for worker in workers:
                    worker.start()
                for worker in workers:
                    worker.join()
                self.assertEqual(send.call_count, 1)
            self.assertEqual(len(results), 4)

    def test_harness_logs_metadata_without_tokens(self):
        with tempfile.TemporaryDirectory() as directory:
            client = oauth.oauth_client(ChatClient, "openai-oauth")(
                model="gpt-test", log_path=Path(directory) / "llm_calls.jsonl")
            self.assertEqual(client.extra_body, {})
            self.assertNotIn("max_tokens", client._body(MESSAGES))
            with patch.dict(os.environ, {"OPENAI_OAUTH_ACCESS_TOKEN": "secret-never-log"}), \
                    patch.object(oauth, "open_request", return_value=sse()):
                result = client.chat(MESSAGES)
            self.assertEqual(result.text, "OK")
            self.assertEqual(result.usage["completion_tokens"], 5)
            for path in Path(directory).glob("*.jsonl"):
                self.assertNotIn("secret-never-log", path.read_text())
            self.assertEqual(json.loads((Path(directory) / "transport.jsonl").read_text())["response_model"], "gpt-test")

    def test_vlm_cache_is_separated_by_model_and_effort(self):
        with tempfile.TemporaryDirectory() as directory:
            client = VLM(backend="openai-oauth", cache_path=Path(directory) / "cache.jsonl")
            questions = {"q": {"type": "choice", "instructions": "Pick", "criteria": {"a": "A"}}}
            out = {"model": "gpt-test", "usage": {}, "choices": [{"message": {"content": '{"q":"a"}'}}]}
            with patch.object(client._oauth, "send", return_value=out) as send:
                for model, think in [("gpt-a", False), ("gpt-a", False), ("gpt-b", False), ("gpt-a", True)]:
                    self.assertEqual(client.ask("state", questions, model=model, key="same", think=think)["answers"]["q"]["choice"], "a")
                self.assertEqual(send.call_count, 3)

    def test_oauth_config_and_resume_mismatch(self):
        args = argparse.Namespace(repo=ROOT/"third_party/robodawn", manifest=ROOT/"robodawn_site/reproduction_manifest.json",
            task="adjust_bottle", episodes=1, start_episode=0, output=None, no_video=True, tier="flex",
            robotwin_root=Path("/content/RoboTwin"), variant="baseline", checker=None, threshold=.5,
            max_steps=3, empty_grasp_limit=0, max_tokens=8000, backend="openai-oauth", model="gpt-test",
            oauth_credentials=None, reasoning_effort="high")
        config, flags = relay.configuration(args)
        self.assertEqual(config["model"], "gpt-test")
        self.assertEqual(config["tier"], "oauth")
        self.assertEqual(flags[flags.index("--model") + 1], "gpt-test")
        self.assertFalse(config["oauth"]["max_output_tokens_sent"])
        self.assertIsNone(config["max_tokens"])
        claude_args = argparse.Namespace(**{**vars(args), "backend": "anthropic-oauth", "model": "claude-opus-5-5"})
        self.assertEqual(relay.configuration(claude_args)[0]["oauth"]["request_profile"], oauth.CLAUDE_COMPAT_VERSION)
        with tempfile.TemporaryDirectory() as directory:
            args.output = Path(directory)
            (args.output/"relay_config.json").write_text(json.dumps(config))
            args.model = "gpt-other"
            with self.assertRaisesRegex(ValueError, "different conditions"):
                relay.configuration(args)
        # Older Vertex metadata has no backend/oauth keys and must still resume.
        args.backend, args.model, args.reasoning_effort, args.output = "vertex", None, None, None
        config, _ = relay.configuration(args)
        with tempfile.TemporaryDirectory() as directory:
            args.output = Path(directory)
            (args.output/"relay_config.json").write_text(json.dumps(config))
            self.assertEqual(relay.configuration(args)[0]["model"], relay.MODEL)

    def test_exact_response_model_check(self):
        self.assertTrue(oauth_experiments.model_matches("gpt-test", "gpt-test-2026-10-10"))
        self.assertFalse(oauth_experiments.model_matches("gpt-test", "gpt-test-mini"))
        self.assertFalse(oauth_experiments.model_matches("gpt-test", None))


if __name__ == "__main__":
    unittest.main()
