"""Offline tests of Clef as the fast model in a slow-planner / fast-executor
split, on RoboDawn's RoboTwin 2.0 demonstrations (third_party/robodawn).

Every demonstration turn has an overview image (10 cm grid, fingertip
markers), the fingertip state, the plan the large VLM wrote for that turn and
the commands it then issued. Clef only picks among options, so each decision
is split into small typed questions asked in one call:

Test A, plan -> command: which arm, which kind of command, and for moves the
direction and a size bin, for gripper commands open/close, for rotations the
axis and sign, for presets which one. Graded against the turn's first command, and leniently against any
command of the turn (the plan often describes several).
    full      the plan as written (often contains target coordinates)
    abstract  the plan with all numbers removed, so the image has to supply them
    abstract_noimg  the same without the image
    noplan    no plan, only the task instruction

Joint variant of test A: one choice among complete commands generated by code
(per arm: six moves, close/open, two presets, yaw both ways, home) plus a size
bin, instead of separate questions that can contradict each other.

Test B, perception: how far the active fingertips are from the object the arm
works on, horizontally and vertically, in bins. The ground truth comes from
the previous turn's "effect" note, which the demonstration tool computed from
simulator poses; the robot never sees it.
    img       image + fingertip state
    noimg     fingertip state only (shows what the prior alone gets)

    uv run python scripts/clef_offline.py [--limit N] [--models clef clef-flash] [--workers 6]
        [--backend openrouter|workers] [--cached-only]
        [--vlms google/gemini-3.8-flash ...] [--think-vlms google/gemini-3.8-flash]

Generative VLMs (OpenRouter) get the same questions and options as text and
answer in JSON, with reasoning off; --think-vlms reruns test B with reasoning
on a subset, to see whether the distances can be read from the image at all.
"""

import argparse
import collections
import glob
import json
import re
from concurrent.futures import ThreadPoolExecutor

import numpy as np

from branchlab import PROJECT_ROOT
from branchlab.clef import MODELS, Clef, image_uri
from branchlab.vlm import VLM

DEMOS = PROJECT_ROOT / "third_party/robodawn/demos/robotwin2/expert"
OUT = PROJECT_ROOT / "outputs/clef_offline"

CONVENTIONS = (
    "Dual-arm robot at a table, seen in the overview image from above and behind the robot. World frame in cm: "
    "+x = to the RIGHT in the image, +y = forward, away from the robot body (UP in the image), +z = up. "
    "The image shows a 10 cm grid on the table with x and y labels along its edges. The LEFT arm's fingertip centre "
    "is marked with a cyan circle, the RIGHT arm's with an orange circle. Table top is at z = {table_z}."
)

ARM = {"left": "the LEFT arm (cyan marker)", "right": "the RIGHT arm (orange marker)"}
KIND = {
    "move": "translate the fingertips straight along one world axis",
    "rotate": "turn the gripper about a world axis (roll, pitch or yaw) in place",
    "point": "snap the gripper to a preset orientation such as pointing down or forward",
    "gripper": "open or close the fingers",
    "home": "send the arm back to its starting pose",
}
MOVE_DIR = {
    "+x": "to the right in the image (+x)",
    "-x": "to the left in the image (-x)",
    "+y": "forward, away from the robot, up in the image (+y)",
    "-y": "back towards the robot, down in the image (-y)",
    "+z": "up, away from the table (+z)",
    "-z": "down, towards the table (-z)",
}
MOVE_SIZE = ["tiny, under 2 cm", "small, 2 to 5 cm", "medium, 5 to 10 cm", "large, 10 cm or more"]
GRIP = {"close": "close the fingers, at least partly, to grasp", "open": "open the fingers to release"}
ROT = {f"{s}{a}": f"rotate about {a}, {'positive' if s == '+' else 'negative'} direction"
       for a in ("yaw", "roll", "pitch") for s in "+-"}
POINT = {"down": "fingers pointing straight down", "forward": "fingers pointing forward (+y)",
         "down45": "fingers tilted 45 degrees down and forward"}
HDIST = ["within 2 cm (directly above or at it)", "2 to 5 cm away", "5 to 15 cm away", "more than 15 cm away"]
VDIST = ["at most 2 cm above it (level with it or lower)", "2 to 6 cm above it", "6 to 15 cm above it",
         "more than 15 cm above it"]


def size_bin(cm):
    cm = abs(cm)
    return 0 if cm < 2 else 1 if cm < 5 else 2 if cm < 10 else 3


def hdist_bin(cm):
    return 0 if cm <= 2 else 1 if cm <= 5 else 2 if cm <= 15 else 3


def vdist_bin(cm):
    return 0 if cm <= 2 else 1 if cm <= 6 else 2 if cm <= 15 else 3


def parse_command(cmd):
    """First command of a turn -> ground-truth labels, or None if not graded."""
    t = cmd.split()
    if t[0] not in ("left", "right") or len(t) < 2:
        return None
    arm, kind = t[0], t[1]
    labels = {"arm": arm, "kind": kind}
    if kind == "move":
        value = float(t[3])
        labels["move_dir"] = ("+" if value > 0 else "-") + t[2]
        labels["move_size"] = size_bin(value)
    elif kind == "rotate":
        labels["rot"] = ("+" if float(t[3]) > 0 else "-") + t[2]
    elif kind == "point":
        labels["point"] = t[2]
    elif kind == "gripper":
        arg = t[2]
        value = 0.0 if arg == "close" else 1.0 if arg == "open" else float(arg)
        labels["grip"] = "close" if value <= 0.6 else "open"
    elif kind != "home":
        return None
    return labels


EFFECT = re.compile(r"(LEFT|RIGHT) fingertips[^;]*?now (\d+(?:\.\d+)?) cm \(horizontal\) / "
                    r"([+-]?\d+(?:\.\d+)?) cm \(vertical\) from the ([^;,]+)")
NUMBERS = [
    re.compile(r"\(\s*[+-]?\d+(?:\.\d+)?\s*,\s*[+-]?\d+(?:\.\d+)?(?:\s*,\s*[+-]?\d+(?:\.\d+)?)?\s*\)"),
    re.compile(r"\b[xyz]\s*=\s*[+-]?\d+(?:\.\d+)?(?:\s*cm)?", re.I),
    re.compile(r"[+-]?\d+(?:\.\d+)?\s*(?:cm|°|deg(?:rees)?)\b", re.I),
    re.compile(r"[+-]?\d+(?:\.\d+)?"),
]


def abstract(plan):
    for pat in NUMBERS:
        plan = pat.sub("", plan)
    plan = re.sub(r"\b(to|by|at|of|around|near)\s+(?=[,.;]|(?:and|to|over|for|on|into)\b|$)", "", plan)
    return re.sub(r"\s+([,.;])", r"\1", re.sub(r"\s{2,}", " ", plan)).strip()


def load_turns():
    turns = []
    for path in sorted(glob.glob(str(DEMOS / "*" / "demo.json"))):
        demo = json.load(open(path))
        name = path.split("/")[-2]
        prev_effect = None
        for i, frame in enumerate(demo["frames"]):
            image = DEMOS / name / frame["images"][0] if frame.get("images") else None
            table = re.search(r"table z = (\d+)", frame.get("state", ""))
            turn = {
                "id": f"{name}#{frame['turn'] if isinstance(frame['turn'], int) else i}",
                "demo": name, "task": demo["instruction"], "image": image,
                "state": frame.get("state", ""), "plan": frame.get("plan", ""),
                "table_z": int(table.group(1)) if table else 74,
                "a": parse_command(frame["commands"][0]) if frame.get("commands") else None,
                "a_all": [c for c in map(parse_command, frame.get("commands") or []) if c],
                "b": None,
            }
            m = EFFECT.search(prev_effect or "")
            if m and m.group(4).strip() not in ("object",):
                turn["b"] = {"arm": m.group(1).lower(), "object": m.group(4).strip(),
                             "hdist": hdist_bin(float(m.group(2))), "vdist": vdist_bin(float(m.group(3)))}
            if image is not None and (turn["a"] or turn["b"]):
                turns.append(turn)
            prev_effect = frame.get("effect")
    return turns


def joint_candidates():
    """Every complete command Clef may pick in the joint harness: per arm, six
    moves, close/open, two presets, yaw both ways, and home."""
    cands = {}
    for arm, mark in (("left", "LEFT arm (cyan)"), ("right", "RIGHT arm (orange)")):
        for d, text in MOVE_DIR.items():
            cands[f"{arm} move {d}"] = f"{mark}: move {text}"
        cands[f"{arm} gripper close"] = f"{mark}: close the fingers to grasp"
        cands[f"{arm} gripper open"] = f"{mark}: open the fingers to release"
        cands[f"{arm} point down"] = f"{mark}: point the fingers straight down"
        cands[f"{arm} point forward"] = f"{mark}: point the fingers forward"
        cands[f"{arm} rotate +yaw"] = f"{mark}: turn the gripper about the vertical axis, positive way"
        cands[f"{arm} rotate -yaw"] = f"{mark}: turn the gripper about the vertical axis, negative way"
        cands[f"{arm} home"] = f"{mark}: return to the starting pose"
    return cands


def joint_label(labels):
    arm, kind = labels["arm"], labels["kind"]
    detail = {"move": labels.get("move_dir"), "gripper": labels.get("grip"),
              "point": labels.get("point"), "rotate": labels.get("rot")}.get(kind)
    return f"{arm} {kind}" + (f" {detail}" if detail else "")


def j_questions():
    return {
        "command": {"type": "choice", "instructions": "Which single command should the robot execute next?",
                    "criteria": joint_candidates()},
        "move_size": {"type": "score", "instructions": "If the next command is a move, how far?",
                      "criteria": MOVE_SIZE},
    }


def a_questions():
    return {
        "arm": {"type": "choice", "instructions": "Which arm does the next command move?", "criteria": ARM},
        "kind": {"type": "choice", "instructions": "What kind of command comes next?", "criteria": KIND},
        "move_dir": {"type": "choice", "instructions": "If the next command is a move, in which direction?",
                     "criteria": MOVE_DIR},
        "move_size": {"type": "score", "instructions": "If the next command is a move, how far?",
                      "criteria": MOVE_SIZE},
        "grip": {"type": "choice", "instructions": "If the next command is a gripper command, which one?",
                 "criteria": GRIP},
        "rot": {"type": "choice", "instructions": "If the next command is a rotation, about which axis and which way?",
                "criteria": ROT},
        "point": {"type": "choice", "instructions": "If the next command is an orientation preset, which one?",
                  "criteria": POINT},
    }


def a_state(turn, condition):
    state = {"conventions": CONVENTIONS.format(table_z=turn["table_z"]), "task": turn["task"],
             "robot_state": turn["state"]}
    if condition == "full":
        state["plan_for_this_step"] = turn["plan"]
    elif condition in ("abstract", "abstract_noimg"):
        state["plan_for_this_step"] = abstract(turn["plan"])
    return state


def b_questions(turn):
    target = f"the {turn['b']['arm'].upper()} arm's fingertips and the {turn['b']['object']}"
    return {
        "hdist": {"type": "score", "instructions": f"Horizontal distance between {target}?", "criteria": HDIST},
        "vdist": {"type": "score", "instructions": f"How high are {target.split(' and ')[0]} above the "
                                                   f"{turn['b']['object']}?", "criteria": VDIST},
    }


def b_state(turn):
    return {"conventions": CONVENTIONS.format(table_z=turn["table_z"]), "task": turn["task"],
            "robot_state": turn["state"]}


def jobs_for(turns, models, vlms=(), think_vlms=(), think_limit=150):
    jobs = []
    for vlm in vlms:
        vlm, _, limit = vlm.partition("@")
        subset = turns[:: max(1, len(turns) // int(limit))][: int(limit)] if limit else turns
        for t in subset:
            if t["a"]:
                jobs.append(("A", "abstract", vlm, t))
                if vlm == "google/gemini-3.8-flash":
                    jobs.append(("A", "noplan", vlm, t))
            if t["b"]:
                jobs.append(("B", "img", vlm, t))
    b_turns = [t for t in turns if t["b"]]
    b_turns = b_turns[:: max(1, len(b_turns) // think_limit)][:think_limit]
    for vlm in think_vlms:
        for t in b_turns:
            jobs.append(("B", "img", vlm + "+think", t))
    for model in models:
        for t in turns:
            if t["a"]:
                for cond in ("full", "abstract", "abstract_noimg", "noplan"):
                    if model != "clef" and cond != "abstract":
                        continue
                    jobs.append(("A", cond, model, t))
                if model == "clef":
                    for cond in ("full", "abstract"):
                        jobs.append(("J", cond, model, t))
            if t["b"]:
                for cond in ("img", "noimg"):
                    if model != "clef" and cond != "img":
                        continue
                    jobs.append(("B", cond, model, t))
    return jobs


def run_job(clients, job):
    test, cond, model, t = job
    clef = clients["clef"] if model in MODELS else clients["vlm"]
    if test == "A":
        state, questions, use_image = a_state(t, cond), a_questions(), cond != "abstract_noimg"
    elif test == "J":
        state, questions, use_image = a_state(t, cond), j_questions(), True
    else:
        state, questions, use_image = b_state(t), b_questions(t), cond == "img"
    images = [image_uri(t["image"])] if use_image else []
    key = f"{test}|{cond}|{model}|{t['id']}"
    try:
        if model in MODELS:
            return job, clef.ask(state, questions, images, model=model, key=key)
        think = model.endswith("+think")
        return job, clef.ask(state, questions, images, model=model.removesuffix("+think"), key=key, think=think)
    except Exception as e:  # keep going; failed calls are counted and left out
        print(f"failed {key}: {str(e)[:120]}", flush=True)
        return job, None


def predicted(answer):
    if answer["type"] == "choice":
        return answer["choice"]
    return int(max(answer["probabilities"], key=answer["probabilities"].get))


def summarize(results):
    rows = collections.defaultdict(lambda: collections.defaultdict(list))
    lat = collections.defaultdict(list)
    for (test, cond, model, t), res in results:
        lat[model].append(res["latency"])
        if test == "J":
            pick = res["answers"]["command"]["choice"]
            r = rows[("A", f"joint-{cond}", model)]
            r["first cmd exact"].append((pick == joint_label(t["a"]), True))
            r["any cmd: arm+kind+dir"].append((any(pick == joint_label(c) for c in t["a_all"]), True))
            if t["a"]["kind"] == "move":
                r["move: arm+kind+dir"].append((pick == joint_label(t["a"]), True))
                r["move_size"].append((predicted(res["answers"]["move_size"]), t["a"]["move_size"]))
            continue
        labels = t["a"] if test == "A" else t["b"]
        for q, truth in labels.items():
            if q not in res["answers"]:
                continue
            pred = predicted(res["answers"][q])
            rows[(test, cond, model)][q].append((pred, truth))
        if test == "A" and labels["kind"] == "move":
            a = res["answers"]
            ok = (predicted(a["arm"]) == labels["arm"] and predicted(a["kind"]) == "move"
                  and predicted(a["move_dir"]) == labels["move_dir"])
            rows[(test, cond, model)]["move: arm+kind+dir"].append((ok, True))
        if test == "A":
            a = res["answers"]
            kind = predicted(a["kind"])
            detail = {"move": "move_dir", "gripper": "grip", "point": "point", "rotate": "rot"}.get(kind)
            guess = f"{predicted(a['arm'])} {kind}" + (f" {predicted(a[detail])}" if detail else "")
            rows[(test, cond, model)]["first cmd exact"].append((guess == joint_label(labels), True))
            hit = any(guess == joint_label(c) for c in t["a_all"])
            rows[(test, cond, model)]["any cmd: arm+kind+dir"].append((hit, True))

    def majority(pairs):
        c = collections.Counter(t for _, t in pairs)
        return c.most_common(1)[0][1] / len(pairs)

    for test in ("A", "B"):
        print(f"\n=== Test {test} ===")
        keys = sorted(k for k in rows if k[0] == test)
        questions = sorted({q for k in keys for q in rows[k]})
        for q in questions:
            line = f"{q:22}"
            base = None
            for k in keys:
                pairs = rows[k].get(q, [])
                if not pairs:
                    continue
                acc = np.mean([p == t for p, t in pairs])
                extra = ""
                if q in ("move_size", "hdist", "vdist"):
                    extra = f" ±1:{np.mean([abs(p - t) <= 1 for p, t in pairs]):.2f}"
                line += f" | {k[1]}/{k[2]}: {acc:.2f}{extra} (n={len(pairs)})"
                if base is None and not q.startswith(("move:", "any cmd", "first cmd")):
                    base = majority(pairs)
            if base is not None:
                line += f" | majority {base:.2f}"
            print(line)
    for model, values in lat.items():
        cost = sum((res.get("usage") or {}).get("cost", 0) or 0 for (_, _, m, _), res in results if m == model)
        print(f"latency {model}: median {np.median(values):.2f}s over {len(values)} calls, cost ${cost:.3f}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=None, help="use only the first N turns")
    parser.add_argument("--models", nargs="*", default=["clef", "clef-flash"])
    parser.add_argument("--workers", type=int, default=6)
    parser.add_argument("--backend", choices=["openrouter", "workers"], default="openrouter")
    parser.add_argument("--vlms", nargs="*", default=[],
                        help="OpenRouter VLM ids for tests A (abstract) and B; 'id@N' limits it to N turns")
    parser.add_argument("--think-vlms", nargs="*", default=[], help="VLMs run with reasoning on test B only")
    parser.add_argument("--think-limit", type=int, default=150)
    parser.add_argument("--cached-only", action="store_true",
                        help="summarize only turns whose calls are all cached; make no new calls")
    args = parser.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    turns = load_turns()
    if args.limit:
        turns = turns[:: max(1, len(turns) // args.limit)][: args.limit]
    print(f"{len(turns)} turns: {sum(1 for t in turns if t['a'])} for test A, "
          f"{sum(1 for t in turns if t['b'])} for test B")
    cache = "responses.jsonl" if args.backend == "workers" else f"responses_{args.backend}.jsonl"
    clef = Clef(cache_path=OUT / cache, backend=args.backend)
    clients = {"clef": clef, "vlm": VLM(cache_path=OUT / "responses_vlm.jsonl")}
    jobs = jobs_for(turns, args.models, args.vlms, args.think_vlms, args.think_limit)
    if args.cached_only:
        key = lambda j: f"{j[0]}|{j[1]}|{j[2]}|{j[3]['id']}"
        complete = collections.defaultdict(lambda: True)
        for j in jobs:
            cache = clef._cache if j[2] in MODELS else clients["vlm"]._cache
            complete[j[3]["id"]] &= key(j) in cache
        jobs = [j for j in jobs if complete[j[3]["id"]]]
        print(f"cached-only: {len({j[3]['id'] for j in jobs})} turns with every call cached")
    print(f"{len(jobs)} calls (cached ones are free)")
    with ThreadPoolExecutor(args.workers) as pool:
        results = list(pool.map(lambda j: run_job(clients, j), jobs))
    failed = sum(1 for _, r in results if r is None)
    if failed:
        print(f"{failed} calls failed after retries and are left out; rerun to fill them in")
    summarize([(j, r) for j, r in results if r is not None])


if __name__ == "__main__":
    main()
